# -*- python -*-
Import("env")
import glob
import os

for src in glob.glob("*.cc"):
    env.Program(src, LIBS=env.getlibs(env["eups_product"]))

# Check for database credentials
import lsst.daf.persistence

if lsst.daf.persistence.DbAuth.available():
    if os.environ.has_key("LSST_DB_AUTH"):
        env["ENV"]["LSST_DB_AUTH"] = os.environ["LSST_DB_AUTH"]
else:
    print "WARNING: No fallback database authenticator seen"
    print "Database tests may be skipped or may fail"


# Tests
import lsst.tests

tests = lsst.tests.Control(env, verbose = True)
tests.run("*.cc")
    
for target in tests.run("MovingObjectPrediction_1.py"):
    env.Depends(target, "../python/lsst/mops/_mopsLib%s" % (env["LDMODULESUFFIX"]))

