# -*- python -*-
Import("env")
import os
import sys

import lsst.tests
import lsst.daf.persistence

env.Program(["MovingObjectPredictionIO_1.cc"], LIBS=env.getlibs("mops"))

if lsst.daf.persistence.DbAuth.available():
#    env["ENV"]["SEAL_PLUGINS"] = os.environ["SEAL_PLUGINS"]    
    if os.environ.has_key("LSST_DB_AUTH"):
        env["ENV"]["LSST_DB_AUTH"] = os.environ["LSST_DB_AUTH"]
else:
    print "WARNING: No fallback database authenticator seen"
    print "Database tests may be skipped or may fail"

tests = lsst.tests.Control(env, verbose = True)
tests.run("*.cc")
    
# set up python tests
for target in tests.run("MovingObjectPrediction_1.py"):
    env.Depends(target, "../python/lsst/mops/_mopsLib%s" % (env["LDMODULESUFFIX"]))

