# -*- python -*-
Import("env")

pkg = env["eups_product"]
env.CheckSwig("python", ilang="c++", includedProducts="utils pex_exceptions daf_base pex_logging pex_policy daf_persistence")
env.LoadableModuleIncomplete("_mopsLib", Split("mopsLib.i"), LIBS=env.getlibs(pkg))

